import test from 'node:test';
import assert from 'node:assert/strict';
import {Session,AttemptStore,step,initialVehicle,FIXTURE} from '../core.mjs';
test('reversing straight preserves heading; brake overrides throttle',()=>{let s=initialVehicle();for(let i=0;i<120;i++)s=step(s,{steer:0,throttle:true,brake:false},-1);assert.ok(s.y>23);assert.equal(s.x,16);assert.equal(s.heading,0);for(let i=0;i<120;i++)s=step(s,{steer:0,throttle:true,brake:true},-1);assert.equal(s.speed,0);});
test('fixed-step input replay is deterministic and articulation stays finite',()=>{const run=()=>{let s=initialVehicle();for(let i=0;i<10000;i++)s=step(s,{steer:Math.sin(i/300),throttle:true,brake:false},i<5000?-1:1);return s;};const a=run();assert.deepEqual(a,run());for(const v of Object.values(a))assert.ok(Number.isFinite(v));});
test('pause clears pedals and stops updates; direction change requires stop',()=>{const s=new Session();s.start('a','now');s.input.throttle=true;s.tick();assert.equal(s.setDirection(1),false);const pose={...s.vehicle};s.pause();assert.equal(s.input.throttle,false);s.tick();assert.deepEqual(s.vehicle,pose);s.resume();s.input.brake=true;for(let i=0;i<30;i++)s.tick();assert.equal(s.setDirection(1),true);});
test('recording contains input changes and observations but never a score',()=>{const s=new Session();s.start('b','now');s.vehicle.x=0;s.tick();s.tick();s.vehicle.x=16;s.tick();s.vehicle.x=0;s.tick();const r=s.finish('reset');assert.equal(r.events.filter(e=>e.type==='synthetic_boundary_entry').length,2);assert.equal(r.inputs.length,1);assert.equal(r.outcome,'reset');assert.equal(r.config.id,FIXTURE.id);assert.equal('score' in r,false);assert.equal(s.finish(),null);});
test('history roundtrip, deduplication, deletion and corruption protection',()=>{const m=new Map();const adapter={getItem:k=>m.get(k),setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)};const store=new AttemptStore(adapter);const s=new Session();s.start('c','now');const r=s.finish();store.save(r);store.save(r);assert.equal(store.read().length,1);const fresh=new AttemptStore(adapter);assert.deepEqual(fresh.read()[0],r);adapter.setItem(store.key,'bad');assert.throws(()=>store.save(r));assert.equal(adapter.getItem(store.key),'bad');store.clear();assert.deepEqual(store.read(),[]);});
test('quota failures are surfaced instead of claiming success',()=>{const store=new AttemptStore({getItem:()=>null,setItem:()=>{throw Error('quota');}});assert.throws(()=>store.save({id:'d',events:[]}));});
